describe('Navigate to administration menus', () => {
  it('Goes to Administration Menu and verify SUb-Menus', () => {
    cy.login('admin')
    cy.goToSubMenu('menuAdministration', 'sousMenuUtilisateurs')
    cy.url().should('include', '/administration-workspace/users/manage')
    cy.goToMenu('menuProjets')
    cy.url().should('include', '/administration-workspace/projects')
    cy.goToMenu('menuJalons')
    cy.url().should('include', '/administration-workspace/milestones')
    cy.goToMenu('menuEntites') 
    cy.url().should('include', '/administration-workspace/entities-customization/custom-fields')
    cy.goToMenu('menuServeurs')
    cy.url().should('include', '/administration-workspace/servers/bugtrackers')
    cy.goToMenu('menuProfils')
    cy.url().should('include', '/administration-workspace/profiles/manage')
    cy.goToMenu('menuSysteme')
    cy.url().should('include', '/administration-workspace/system/information?anchor=information')
    cy.goToMenu('exit')
    cy.url().should('include', '/home-workspace')
    cy.logout()
  })
})